# 工作流名称
name: 提交同步镜像至指定仓库

# 工作流运行时显示名称
run-name: ${{ github.actor }} Sync Docker to Hub by Push

# 怎样触发工作流
on:
  # 推送时触发
  push:
    # 触发分支为sync
    branches:
      - main
    # 触发路径为
    paths:
      - images.txt

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  # 这个任务为 sync_docker_by_push
  sync_docker_by_push:
    name: Sync Images to DockerHub
    # 使用什么环境运行
    runs-on: ubuntu-latest
    # 步骤表示将作为作业的一部分执行的一系列任务
    steps:
      # 签出存储库，以便你的工作可以访问它
      - name: Check out code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Action to login against a Docker registry.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          logout: true

      # Runs a set of commands using the runners shell
      - name: Pull and Push Images
        run: |
          sh image_sync.sh ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}